create feature-classification_dataset
eora-ai/torchok pull request #12
Opened 2022-04-06 07:02 UTC by VladislavPatrushev

create feature-classification_dataset

2022-04-06 15:58 UTC, VladVin requested changes

2022-04-06 15:58 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +                 expand_rate: int = 1,
Remove support of expand rate

2022-04-06 15:58 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +                 num_classes: int = None,
`num_classes` must be a required param

2022-04-06 15:58 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +            raise Exception(f'Target column contain label: {max_label}, it\'s more than num_classes = {num_classes}')
`raise ValueError`

2022-04-06 15:58 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +        sample['target'] = record[self.target_column]
Add method `process_multiclass` where you will check the class index to fit the range

2022-04-06 15:58 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +    def process_multilabel(label: Union[int, str], num_classes: int) -> np.array:
Add documentation what formats of input this method supports.  
Make it private

2022-04-06 15:58 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +    def target_column(self) -> str:
Move all properties to the end of class definition

2022-04-06 15:58 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +            multilabel: If True, target labels is being converted to multihot vector for multilabel task.
`If True, target labels are being converted to multihot vector for multilabel task.`

2022-04-06 15:58 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +            num_classes: Number of classes for multilabel task(length of multihot target vector).
`Number of classes (i.e. maximum class index in the dataset).`

2022-04-06 15:58 UTC, VladVin commented on tests/data/test_image_classification.py
> +        self.transform = Compose([Resize(224, 224), ToTensorV2()], p=1.0)
Add augmentations

2022-04-06 15:58 UTC, VladVin commented on tests/data/test_image_classification.py
> +    def test_shape_default(self):
`test_shape_when_transformed`

2022-04-06 15:58 UTC, VladVin commented on tests/data/test_image_classification.py
> +        self.assertEqual(list(self.ds[0]['input'].shape), [1, 224, 224])
Without `list`

2022-04-06 15:58 UTC, VladVin commented on tests/data/test_image_classification.py
> +    def test_input_test_mode_false(self):
`test_getitem_when_test_mode_false`

2022-04-06 15:58 UTC, VladVin commented on tests/data/test_image_classification.py
> +                                             num_classes=9, lazy_init_multilabel=True)
Put `num_classes`

2022-04-06 15:58 UTC, VladVin commented on tests/data/test_image_classification.py
> +    def test_input_dtype(self):
Add test: `test_target_dtype_when_specified`

2022-04-07 18:20 UTC, VladislavPatrushev commented on src/data/datasets/classification/image_classification.py
> +        image_path = record[self.input_column]
Maybe send idx to __read_image ?

2022-04-07 19:33 UTC, VladVin requested changes

2022-04-07 19:33 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +        if self.lazy_init:
`self.__lazy_init`

2022-04-07 19:33 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +            if self.multilabel:
`self.__multilabel`

2022-04-07 19:33 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +                        If False, dataset prepare target for multiclass classification.
prepares targets

2022-04-07 19:33 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +                 test_mode: Optional[bool] = False,
Remove `Optional`

2022-04-07 19:33 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +            raise ValueError(f'Target column contain class index: {class_idx}, ' +
`contains`

2022-04-07 19:33 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +            raise ValueError(f'Target column contain class index: {class_idx}, ' +
Replace + by \

2022-04-07 19:33 UTC, VladVin commented on src/data/datasets/classification/image_classification.py
> +    """A generic dataset for multilabel/multiclass image classification task"""
Put 2 examples of tables for multiclass and multilabel tasks

2022-04-07 19:33 UTC, VladVin commented on src/data/datasets/base.py
> +        self.__csv = pd.read_csv(self.data_folder / csv_path)
Move to child classes, put `dtype` for each known column.  
`self.__csv = pd.read_csv(self.data_folder / csv_path, dtype={'input_column': str, 'target_column': int or str})`

2022-04-07 19:33 UTC, VladVin commented on tests/datasets/data/multiclass_test.csv
> +image_path,label
Remove files above 100 KB

2022-04-07 19:33 UTC, VladVin commented on tests/datasets/test_image_classification.py
> +        self.data_folder = os.getcwd() + '/tests/datasets/data/'
Use pathlib and `__file__`: https://stackoverflow.com/a/63313758/3300539

2022-04-08 15:03 UTC, VladVin requested changes

2022-04-08 15:03 UTC, VladVin commented on tests/datasets/test_image_classification.py
> +import os
Move tests to `tests/data/datasets/...`

2022-04-11 14:05 UTC, VladVin commented on src/data/datasets/base.py
> +        self.__valid_transform_params = ['image', 'mask', 'bboxes']
Remove this error check

2022-04-11 14:26 UTC, VladVin approved these changes

2022-04-11 14:27 UTC, merged