Fix bugs
eora-ai/torchok pull request #126
Opened 2022-09-06 14:16 UTC by PososikTeam

2022-09-07 09:33 UTC, VladVin requested changes

2022-09-07 09:48 UTC, Animatory commented on torchok/__main__.py
> +            for i in range(len(config.optimization)):
PL does not support several optimizers. Throw error if got this more than one optimizers

2022-09-07 10:04 UTC, Animatory commented on torchok/tasks/base.py
> +        optim = self.optimizers()
Remove

2022-09-07 10:04 UTC, Animatory commented on torchok/constructor/config_structure.py
> +class LoadCheckpointParams:
Move in TaskParams

2022-09-07 10:09 UTC, PososikTeam commented on torchok/__main__.py
> +                config.optimization[i].optimizer.params.lr = suggested_lr
Yes it's a common way. https://pytorch-lightning.readthedocs.io/en/1.4.5/advanced/lr_finder.html#:~:text=model%20%3D%20MyModelClass(hparams,trainer.fit(model)

2022-09-08 09:57 UTC, Animatory approved these changes

2022-09-09 18:44 UTC, VladVin approved these changes

2022-09-09 18:45 UTC, merged