Feature retrieval dataset
eora-ai/torchok pull request #15
Opened 2022-04-13 18:11 UTC by VladislavPatrushev

2022-04-13 20:30 UTC, VladVin requested changes

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/db_retrieval_dataset.py
> +            img_paths_csv_path: path to mapping image identifiers to image paths. Format: id | path.
Explain that this is related to matches csv

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/db_retrieval_dataset.py
> +        self.__include_only = pd.read_csv(Path(db_folder) / include_only_path, usecols=["id", input_column],
`Path(db_folder)` -> `self.__db_folder`  
`input_column` -> `self.__input_column`

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/db_retrieval_dataset.py
> +                                          dtype={"id": str, input_column: str}, header=0)
`"id": int`

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/db_retrieval_dataset.py
> +        self._objid2paths.update(self.__db_objid2paths)
Make `imgid2path` separate for matches and gallery

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/db_retrieval_dataset.py
> +        sample = super().__getitem__(index)
```
If index < self._n_query + self._n_relevant:
    sample = super().__getitem__(index)
else:
    # take from gallery mapping
```

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/db_retrieval_dataset.py
> +    """
Explain how the targets are constructed

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/db_retrieval_dataset.py
> +            self.__targets[index, 0] = 1.
Make two separate tensors at output: one for relevant scores (`scores`), another is a boolean tensor of query indicators (`is_query`)

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/db_retrieval_dataset.py
> +        self.__targets = np.zeros((len(self), 1 + self._n_queries), dtype=np.float32)
Use `torch.zeros`

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/db_retrieval_dataset.py
> +            relevant_indices = np.array([self.__objid2index[obj_id] for obj_id in relevant_obj_idxs])
`torch.Tensor`

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/each_to_each_retrieval_dataset.py
> +        sample['index'] = index
Create `scores` and `is_query` as in the gallery retrieval dataset

2022-04-13 20:30 UTC, VladVin commented on src/data/datasets/representation/each_to_each_retrieval_dataset.py
> +
Create one class with defaults `gallery_*` arguments set to empty values. In the default case each query will be searched for relevant while the gallery is a set of the remaing items (both queries and relevant)

2022-04-19 15:43 UTC, VladVin requested changes

2022-04-19 15:43 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +                 input_column: str = 'image_path',
Add columns for all csv's as a dict of all possible column mappings

2022-04-19 15:43 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +            self.__gallery_folder = gallery_folder
Put out of condition

2022-04-22 08:41 UTC, PososikTeam commented on src/data/datasets/representation/validation.py
> +        self.__parse_match_csv()
It's a bad practice to generate some class parameters in another method, without return these parameters as function return values. If you return that values you can write in documentation that exactly return your function, without it code would be unclear to read.

2022-04-22 09:15 UTC, PososikTeam commented on src/data/datasets/representation/validation.py
> +            self.__relevance_scores.append([])
We need to define for our team, what is the best way to append new generated list in another base list. I see that constructor first time, and for me it was unclear to read. But if Vlad approve it ok.
Usually i do:
`base_list = []
 for ... :
     curr_added_list = generate_list()
     base_list.append(curr_added_list)
`

2022-04-22 10:05 UTC, PososikTeam commented on src/data/datasets/representation/validation.py
> +        scores = torch.zeros((len(self), self.__n_queries), dtype=torch.float32)
Please, explain me why it shape is `(len(self), self.__n_queries)` but not `(len(self), len(self))`.

2022-04-22 10:06 UTC, PososikTeam commented on src/data/datasets/representation/validation.py
> +
I think in getitem we must write return dict parameters documentation.

2022-04-26 14:16 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +    a higher score corresponds to a greater similarity.
Add "(must be float value > 0.)"

2022-04-26 14:17 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +    Query ids should be unique, otherwise the rows having the same query id will be treated as different matches.
"Query ids should be unique..." -> "Query ids should be unique int values..."

2022-04-26 14:21 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +        self._imgid2paths = dict(zip(self.__img_paths[self.__img_list_map_column['img_id']],
Since there is only one path for each image id, you can rename the dict to `self._imgid2path` for consistency

2022-04-26 14:26 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +    Where gallery items are treated non-relevant.
Looks cluttered and also the first line repeats dataset definition. Better to leave just one line `Dataset for image retrieval validation ...`

2022-04-26 14:27 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +        self.__gallery_folder = gallery_folder
`self.__gallery_folder = Path(gallery_folder)`

2022-04-26 14:27 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +            self.__gallery_paths = pd.read_csv(Path(self.__gallery_folder) / self.__gallery_list_csv_path,
`Path(self.__gallery_folder)` -> `self.__gallery_folder`

2022-04-26 14:31 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +            sample['image'] - image
`Tensor, representing image after augmentations and transformations, dtype=image_dtype`

2022-04-26 14:35 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +                 use_gallery: Optional[bool] = False,
You can remove this argument - when a user specifies `gallery_folder` we can automatically derive that this is a gallery mode

2022-04-26 14:39 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +            gallery_folder: path to a folder with all gallery images (traversed recursively)
Add also: `When the gallery not specified all the remaining queries and relevant will be considered as negative samples to a given query-relevant set`

2022-04-26 15:18 UTC, PososikTeam commented on src/data/datasets/representation/validation.py
> +            relevant_arr.append([])
Please, use empty list and append it on main list.

2022-04-29 14:14 UTC, VladVin requested changes

2022-04-29 14:14 UTC, VladVin commented on src/data/datasets/representation/validation.py
> +                relevant_arr[-1].append(img_id)
Should be appended to higher level list

2022-05-01 19:27 UTC, VladVin approved these changes

2022-05-01 19:27 UTC, merged