Update freeze_unfreeze callback
eora-ai/torchok pull request #155
Opened 2022-10-31 12:07 UTC by Animatory

2022-11-01 12:13 UTC, PososikTeam commented on torchok/callbacks/freeze_unfreeze.py
> +                `module_name` (int): module name relative to the task on which freeze will be applied.
(str)

2022-11-01 12:50 UTC, PososikTeam commented on torchok/callbacks/freeze_unfreeze.py
> +            parents = [i.__name__ for i in inspect.getmro(type(mod))]
Cool method)

2022-11-01 12:56 UTC, PososikTeam requested changes
Great work! Please change module_name (int) -> module_name (str) in documentation.

2022-11-02 10:21 UTC, Animatory commented on torchok/callbacks/freeze_unfreeze.py
> +                `module_name` (int): module name relative to the task on which freeze will be applied.
fixed

2022-11-02 11:01 UTC, PososikTeam approved these changes

2022-11-02 11:01 UTC, merged