Feature ResNet, SEResNet
eora-ai/torchok pull request #26
Opened 2022-05-04 14:36 UTC by VladislavPatrushev

2022-05-06 13:50 UTC, PososikTeam commented on src/models/modules/bricks/activations/activations_me.py
> +""" Activations (memory-efficient w/ custom autograd)
Do we really need this functions?

2022-05-06 13:58 UTC, PososikTeam commented on src/models/modules/utils/create_attn.py
> +def create_attn(attn_type, channels, **kwargs):
Documentation

2022-05-06 13:58 UTC, PososikTeam commented on src/models/modules/utils/create_attn.py
> +def get_attn(attn_type):
Documentation

2022-05-06 13:59 UTC, PososikTeam commented on src/models/modules/utils/create_attn.py
> +from src.models.modules.blocks.se import SEModule
Strage things that SE block need in utils. May be replace file?

2022-05-06 14:52 UTC, PososikTeam commented on src/models/backbones/utils/hub.py
> +import json
I think this module would be rewrited.

2022-05-06 14:53 UTC, PososikTeam commented on src/models/backbones/utils/helpers.py
> +""" Model creation / weight loading / state_dict helpers
I think this file will be overwritten.

2022-05-06 14:59 UTC, PososikTeam commented on src/models/backbones/utils/helpers.py
> +def build_model_with_cfg(
I think you need rewrite this method...

2022-05-06 15:01 UTC, PososikTeam commented on src/models/backbones/utils/registry.py
> +import fnmatch
Is we really need this?

2022-05-06 15:04 UTC, PososikTeam commented on src/models/modules/blocks.py
> -# Higher level modules like SE (Squeeze Excitation)
Remove, add comment in __init__.py

2022-05-06 15:08 UTC, PososikTeam commented on src/models/modules/bricks.py
>  # Low level modules like ConvBnAct
Move to briks directory

2022-05-06 15:09 UTC, PososikTeam commented on src/models/modules/bricks.py
> +class CondConv2d(nn.Module):
Documentation

2022-05-06 15:13 UTC, PososikTeam commented on src/models/modules/bricks.py
> +def get_condconv_initializer(initializer, num_experts, expert_shape):
Documentation. And check if it possible to use python @. 
https://realpython.com/primer-on-python-decorators/#:~:text=%40my_decorator%0Adef%20say_whee()%3A%0A%20%20%20%20print(%22Whee!%22)

2022-05-06 15:19 UTC, PososikTeam commented on src/models/modules/bricks/conv2d_same.py
> +"""TorchOK Conv2d w/ Same Padding
I think we need create new folder for model bricks.

2022-05-06 15:19 UTC, PososikTeam commented on src/models/modules/bricks/conv2d_same.py
> +def conv2d_same(
Documentation.

2022-05-06 15:20 UTC, PososikTeam commented on src/models/modules/bricks/conv2d_same.py
> +class Conv2dSame(nn.Conv2d):
Documentation.

2022-05-06 15:20 UTC, PososikTeam commented on src/models/modules/bricks/conv2d_same.py
> +def create_conv2d_pad(in_chs, out_chs, kernel_size, **kwargs):
Documentation.

2022-05-06 15:37 UTC, PososikTeam commented on src/models/modules/utils/config.py
> +""" Model / Layer Config singleton state
Do we really need this file?

2022-05-06 15:38 UTC, PososikTeam commented on src/models/modules/utils/create_act.py
> +"""TorchOK Activation Factory.
Do we really need this file, if yes replace it in briks path and add documentation.

2022-05-06 15:41 UTC, PososikTeam commented on src/models/modules/utils/padding.py
> +""" Padding Helpers
Add documentation.

2022-05-06 15:42 UTC, PososikTeam commented on src/models/modules/utils/helpers.py
> +"""Layer/Module Helpers
Add documentation.

2022-05-13 06:38 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +        super(Bottleneck, self).__init__()
`super().__init__()`

2022-05-13 06:38 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +        super(BasicBlock, self).__init__()
`super().__init__()`

2022-05-13 06:39 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +        super(ResNet, self).__init__()
`super().__init__()`

2022-05-13 06:40 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +    def __make_layer(self,
Documentation

2022-05-13 06:49 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +        self.conv1 = nn.Conv2d(in_chans, self.channels[0], kernel_size=7, stride=2, padding=3, bias=False)
Why not create ConvBnAct in briks?

2022-05-13 06:54 UTC, PososikTeam commented on src/models/backbones/utils/helpers.py
> +""" TorchOK Model creation / weight loading / state_dict helpers
Do we still need all of this file? Can we shorten it?

2022-05-13 06:54 UTC, PososikTeam commented on src/models/backbones/utils/helpers.py
> +def load_state_dict(checkpoint_path, use_ema=False):
Documentation

2022-05-13 06:54 UTC, PososikTeam commented on src/models/backbones/utils/helpers.py
> +def adapt_input_conv(in_chans: int, conv_weight):
Documentation

2022-05-13 06:59 UTC, PososikTeam commented on src/models/backbones/utils/helpers.py
> +def load_pretrained(model: nn.Module,
I think this method must be overwritten

2022-05-13 07:10 UTC, PososikTeam commented on src/models/backbones/utils/helpers.py
> +    if input_convs is not None and in_chans != 3:
It's good feature to load weights from rgb Model to grayscale Model. It must be save.

2022-05-13 07:13 UTC, PososikTeam commented on src/models/backbones/utils/helpers.py
> +def set_default_kwargs(kwargs: dict,
Documentation

2022-05-13 07:24 UTC, PososikTeam commented on src/models/backbones/utils/helpers.py
> +        except TypeError:
Why need tru except? I think need calls only `state_dict = filter_fn(state_dict)`. And also question is we need filter_fn?

2022-05-17 14:21 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +        self.conv = nn.Conv2d(out_channels, out_block_channels, kernel_size=3, padding=1, bias=False)
How you look at idea to add functional in ConvBnAct to create briks without activation layer. So you can add ConvBnAct for conv and bn too.

2022-05-17 14:22 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +        self.conv = nn.Conv2d(out_channels, out_block_channels, kernel_size=1, stride=1, bias=False)
Same thing to create ConvBnAct with possibility to not include activation.

2022-05-17 14:24 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +            block: Type of block.
Class?

2022-05-17 14:43 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +            downsample = nn.Sequential(
good point about the circle

2022-05-17 14:53 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +        """Create layer - abstraction for convenient work.
Create Resnet module which contain downsample and one of BasicBlock or Bottleneck modules.

2022-05-17 14:53 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +            block: Abstraction for convenient work.
Block type class.

2022-05-17 14:55 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +    def get_features_info(self, output_channels, module_names, strides):
Typing and documentation

2022-05-17 14:55 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +    def get_forward_output_channels(self) -> Union[int, List[int]]:
Typing and documentation

2022-05-19 08:54 UTC, PososikTeam commented on src/models/backbones/resnet.py
> +            downsample = nn.Sequential(
Why we still need nn.Sequential?

2022-05-19 14:58 UTC, VladVin requested changes

2022-05-19 14:58 UTC, VladVin commented on src/models/modules/bricks/convbnact.py
> +                 act_layer: nn.Module = nn.ReLU):
Make it optional. And below when it's called just check for None. Using `nn.Identity` isn't a common style

2022-05-19 14:58 UTC, VladVin commented on src/models/backbones/utils/helpers.py
> +            state_dict[input_convs] = adapt_input_conv(in_chans, state_dict[input_convs])
Remove this

2022-05-19 14:58 UTC, VladVin commented on src/models/modules/blocks/se.py
> +    def __make_divisible(self, value, divisor=8, min_value=None):
Put typings

2022-05-19 14:58 UTC, VladVin commented on tests/models/backbones/test_backbones.py
> +# class TestSEResNet50(unittest.TestCase):
I would suggest to remove at all, because the code snippet is very similar to the above code

2022-05-20 16:56 UTC, merged